## Filtered Archive

In [3]:
# IMPORTS AND PREAMBLE
import pandas as pd

In [64]:
# READ IN CSV FILE
archive = pd.read_csv(r'C:\Users\liamh\OneDrive - Cardiff University\Modules\Exomoons\Archive\Exoplanet_Archive.csv')
#archive


# LISTING ALL COLUMNS FOR EASY ACCESS TO COLUMNS
list(archive.columns.values.tolist()) 
#print('Done.')

In [77]:
# FILTERING OUT MASSES LESS THAN 0.5 
archive.massj = df['pl_bmassj']
mass_filt = df[archive.massj >= 0.5] # KEEPS ROWS THAT HAVE MASS GREATER THAN OR EQUAL TO 0.5 JUPITER RADII
#mass_df
print('Done.')

Done.

In [84]:
#pd.set_option('display.max_columns', None) # PRINTS WHOLE TABLE OF COLUMNS
#pd.set_option('display.max_rows', None) # PRINTS WHOLE TABLE OF ROWS

mass_filt.method = mass_filt['discoverymethod'] # GIVES 'discoverymethod' COLUMN OWN DATAFRAME
disc_and_mass = mass_filt[mass_filt['discoverymethod'].str.contains('Transit')] # FILTERS ROWS THAT HAVE THE WORD 'transit' IN
#disc_and_mass
print('Done.')

Done.

## Calculating the CHZ
#### Using Equations from page 10 in Kopparapu et al (2013)
###### https://iopscience.iop.org/article/10.1088/0004-637X/765/2/131/pdf#page=10.44

In [89]:
T = disc_and_mass['st_teff'] - 5780

# Recent Venus
a_v = 1.4316e-4
b_v = 2.9875e-9
c_v = -7.5702e-12
d_v = -1.1635e-15

VS_eff = 1.7753 + (a_v*T) + (b_v*T**2) + (c_v*T**3) + (d_v*T**4)


# Early Mars
a_m = 5.4513e-5
b_m = 1.5313e-9
c_m = -2.7786e-12
d_m = -4.8997e-16

MS_eff = 0.3179 + (a_m*T) + (b_m*T**2) + (c_m*T**3) + (d_m*T**4)

#print(VS_eff, MS_eff)
print('Done.')

Done.

In [94]:
L = 10**(disc_and_mass['st_lum'])

in_CHZ = (L/VS_eff)**0.5
out_CHZ = (L/MS_eff)**0.5

#print('Inner CHZ:\n{} \n\nOuter CHZ: \n{}'.format(in_CHZ,out_CHZ))
#in_CHZ_df = pd.DataFrame[in_CHZ]
#out_CHZ_df = pd.DataFrame[out_CHZ]
print('Done.')

Done.

In [96]:
# ADDING THE NEW CHZ COLUMNS TO THE FILTERED DATAFRAME
filtered_df['in_CHZ'] = in_CHZ
filtered_df['out_CHZ'] = out_CHZ

filtered_df

C:\Users\liamh\AppData\Local\Temp\ipykernel_13416\2038381713.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['in_CHZ'] = in_CHZ
C:\Users\liamh\AppData\Local\Temp\ipykernel_13416\2038381713.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['out_CHZ'] = out_CHZ

,rowid,pl_name,hostname,pl_letter,hd_name,hip_name,tic_id,gaia_id,sy_snum,sy_pnum,...,sy_kepmagerr2,sy_kepmag_reflink,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,in_CHZ,out_CHZ
89,90,CoRoT-1 b,CoRoT-1,b,NaN,NaN,TIC 36352297,Gaia DR2 3105507886130792448,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,6,1,0,5,20,1.050514,2.463741
90,91,CoRoT-10 b,CoRoT-10,b,NaN,NaN,TIC 405010127,Gaia DR2 4263752921128319616,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,0,0,0,0,0,0.334638,0.817680
91,92,CoRoT-11 b,CoRoT-11,b,NaN,NaN,TIC 110178537,Gaia DR2 4285511294172309504,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,0,0,0,0,0,1.130398,2.598429
92,93,CoRoT-12 b,CoRoT-12,b,NaN,NaN,TIC 280210963,Gaia DR2 3107255598526406912,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,0,0,0,0,0,0.816969,1.939931
93,94,CoRoT-13 b,CoRoT-13,b,NaN,NaN,TIC 281909674,Gaia DR2 3101974231859723776,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,0,0,0,0,0,0.810939,1.902291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5616,5617,XO-3 b,XO-3,b,NaN,NaN,TIC 8400842,Gaia DR2 470650560777348352,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,1.0,50,4,0,5,0,1.649701,3.793718
5617,5618,XO-4 b,XO-4,b,NaN,NaN,TIC 51234631,Gaia DR2 990291507088739072,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,11,1,0,2,0,1.358046,3.126820
5618,5619,XO-5 b,XO-5,b,NaN,NaN,TIC 9155187,Gaia DR2 920308932010648448,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,26,2,0,0,0,0.710389,1.706387
5619,5620,XO-6 b,XO-6,b,NaN,NaN,TIC 138168780,Gaia DR2 1114308481600798336,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,0,0,0,0,0,1.342817,3.056267
5620,5621,XO-7 b,XO-7,b,NaN,NaN,TIC 268403451,Gaia DR2 2303332931542914048,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,0,0,0,0,0,1.210062,2.802250

Assuming that the orbits follow a Keplarian orbit, the orbit semi-major axis is mean distance from its parent star in AU.

In [100]:
# FILTERS OUT PLANETS WITH ORBITAL SEPARATION OUTSIDE THIS CALCULATED RANGE OF CHZ

filtered_archive = filtered_df[(filtered_df['pl_orbsmax'] >= filtered_df['in_CHZ']) & (filtered_df['pl_orbsmax'] <= filtered_df['out_CHZ'])]
filtered_archive
#print('Done.')

,rowid,pl_name,hostname,pl_letter,hd_name,hip_name,tic_id,gaia_id,sy_snum,sy_pnum,...,sy_kepmagerr2,sy_kepmag_reflink,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,in_CHZ,out_CHZ
2875,2876,Kepler-1647 b,Kepler-1647,b,NaN,NaN,TIC 170344769,Gaia DR2 2073793420945053824,2,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,1.0,0,0,0,0,0,1.548719,3.592337
2952,2953,Kepler-1704 b,Kepler-1704,b,NaN,NaN,TIC 350738167,Gaia DR2 2136191736602006016,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0.0,0,0,0,0,0,1.264619,2.993113
2955,2956,Kepler-1708 b,Kepler-1708,b,NaN,NaN,TIC 272716898,Gaia DR2 2078801971283008128,1,1,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,1.0,0,0,0,0,0,0.911720,2.119406
3949,3950,Kepler-419 c,Kepler-419,c,NaN,NaN,TIC 27454084,Gaia DR2 2135604425595213440,1,2,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,NaN,0,0,0,0,0,1.662990,3.824131
4149,4150,Kepler-553 c,Kepler-553,c,NaN,NaN,TIC 264508613,Gaia DR2 2086498312157538688,1,2,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,1.0,0,0,0,0,0,0.562493,1.366741
5283,5284,TOI-4600 c,TOI-4600,c,NaN,NaN,TIC 232608943,Gaia DR2 1631416599805196544,1,2,...,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,2.0,0,0,0,0,0,0.498281,1.211949

In [110]:
# TEST TO SEE IF THE MASS > 0.5 JUPITER MASS AND SEPARATION IS WITHIN THE CALCULATED CIRCUMSTELLAR HABITABLE ZONE
test = filtered_archive[['pl_name','pl_bmassj','pl_orbsmax','in_CHZ','out_CHZ']]
test

            pl_name  pl_bmassj  pl_orbsmax    in_CHZ   out_CHZ
2875  Kepler-1647 b    1.51968      2.7205  1.548719  3.592337
2952  Kepler-1704 b    4.16000      2.0270  1.264619  2.993113
2955  Kepler-1708 b    4.60000      1.6400  0.911720  2.119406
3949   Kepler-419 c    7.30000      1.6800  1.662990  3.824131
4149   Kepler-553 c    6.70000      0.8980  0.562493  1.366741
5283     TOI-4600 c    9.27000      1.1520  0.498281  1.211949